### GET /
GET http://localhost:8383

###
POST http://localhost:8383/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}



###

POST http://localhost:8383/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}