# POST http://localhost:5000/api/products
# Content-Type: application/json

# {
#   "name": "testuser",
#   "price": 299,
#   "image":"https/das/das.com"
# }
 
 ## GET
GET http://localhost:5000/api/products
Content-Type: application/json



#
# DELETE http://localhost:5000/api/products/679681f54e9a5f9874a7c1b1


